#enforces min / max / default values for containers (requests & limits) when a user creates Pods in a namespace.

apiVersion: v1
kind: LimitRange
metadata:
name: lr-user
namespace: user-<USERNAME>
spec:
limits:
- type: Container
defaultRequest:
cpu: "250m"
memory: 256Mi
default:
cpu: "1"
memory: 1Gi
max:
cpu: "2"
memory: 2Gi
min:
cpu: "100m"
memory: 128Mi